<?php

namespace DepartmentSite\DictionaryBundle\Repository;

/**
 * DictionaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DictionaryRepository extends \Doctrine\ORM\EntityRepository
{
}
