<?php

namespace DepartmentSite\DictionaryBundle\Repository;

/**
 * DictionaryTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DictionaryTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
