project_index:
    path:     /
    defaults:
        _controller: "DepartmentSiteProjectBundle:Project:index"
        locale: ru
    methods:  GET
    requirements: ru|en

project_show:
    path:     /{id}/show
    defaults:
        _controller: "DepartmentSiteProjectBundle:Project:show"
        locale: ru
    methods:  GET
    requirements: ru|en

project_new:
    path:     /new
    defaults: { _controller: "DepartmentSiteProjectBundle:Project:new" }
    methods:  [GET, POST]

project_edit:
    path:     /{id}/edit
    defaults: { _controller: "DepartmentSiteProjectBundle:Project:edit" }
    methods:  [GET, POST]

project_delete:
    path:     /{id}/delete
    defaults: { _controller: "DepartmentSiteProjectBundle:Project:delete" }
    methods:  DELETE
