project_index:
    path:     /
    defaults:
        _controller: "DepartmentSiteProjectBundle:Project:index"
        _locale: ru
    methods:  GET
    requirements:
        _locale: ru|en

project_show:
    path:     /{slug}/show
    defaults:
        _controller: "DepartmentSiteProjectBundle:Project:show"
        _locale: ru
    methods:  GET
    requirements:
        _locale: ru|en

project_new:
    path:     /new
    defaults: { _controller: "DepartmentSiteProjectBundle:Project:new" }
    methods:  [GET, POST]


project_edit:
    path:     /{slug}/edit
    defaults: { _controller: "DepartmentSiteProjectBundle:Project:edit" }
    methods:  [GET, POST]


project_delete:
    path:     /{slug}/delete
    defaults: { _controller: "DepartmentSiteProjectBundle:Project:delete" }
    methods:  DELETE
