notice_index:
    path:     /{page}/
    defaults:
        _controller: "DepartmentSiteNoticeBundle:Notice:index"
        _locale : ru
        page : 1
        methods:  GET
        requirements:
            _locale : ru|en

notice_show:
    path:     /{slug}/show
    defaults:
        _controller: "DepartmentSiteNoticeBundle:Notice:show"
        _locale : ru
    methods:  GET
    requirements:
                _locale : ru|en



