services:
    dictionary.twig_extension:
        class: DepartmentSite\DictionaryBundle\Twig\DictionaryExtension
        calls:
            - [setContainer, ["@service_container"]]
        public: false
        tags:
            - { name: twig.extension }

    admin.dictionary:
        class: DepartmentSite\DictionaryBundle\Admin\DictionaryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Dictionary", label: "Dictionary" }
        arguments: [~, DepartmentSite\DictionaryBundle\Entity\Dictionary, ~]
        calls:
             - [ setTranslationDomain, [DepartmentSiteNewsBundle]]