gallery_index:
    path:     /{page}/
    defaults:
      _controller: "DepartmentSiteGalleryBundle:Gallery:index"
      _locale : ru
      page : 1
    methods:  GET
    requirements:
        _locale : ru|en


gallery_show:
    path:     /{id}/show
    defaults:
          _controller: "DepartmentSiteGalleryBundle:Gallery:show"
          _locale : ru
    methods:  GET
    requirements:
        _locale : ru|en
