<?php

namespace DepartmentSite\SlideShowBundle\Repository;

/**
 * SlideShowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlideShowRepository extends \Doctrine\ORM\EntityRepository
{
}
