<?php

namespace DepartmentSite\MenuBundle\Repository;

/**
 * BannerMenuTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerMenuTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
