<?php

namespace DepartmentSite\MenuBundle\Repository;

/**
 * BannerMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerMenuRepository extends \Doctrine\ORM\EntityRepository
{
}
