<?php

namespace DepartmentSite\MenuBundle\Repository;

/**
 * HeaderMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HeaderMenuRepository extends \Doctrine\ORM\EntityRepository
{
}
