<?php

namespace DepartmentSite\MenuBundle\Repository;

/**
 * HeaderMenuTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HeaderMenuTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
