<?php

namespace DepartmentSite\MenuBundle\Repository;

/**
 * SideBarMenuTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SideBarMenuTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
