imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@DepartmentSiteNewsBundle/Resources/config/services.yml" }
    - { resource: "@DepartmentSiteNewsBundle/Resources/config/admin.yml" }
    - { resource: "../../vendor/knplabs/doctrine-behaviors/config/orm-services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
          json: Sonata\Doctrine\Types\JsonType
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                mappings:
                    ApplicationSonataUserBundle: ~
                    DepartmentSiteNewsBundle: ~
                    SonataUserBundle: ~
                    FOSUserBundle: ~

        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

iphp_file_store:
    mappings:
       photo:
           upload_dir:  "%kernel.root_dir%/../web/photo"
           upload_path: /photo
           directory_namer:
               date:
                  params: { field : createdAt, depth : month }
           namer: ~

sonata_block:
    default_contexts: [cms]
    blocks:
      # Enable the SonataAdminBundle block
      sonata.admin.block.admin_list:
        contexts:  [admin]
      sonata.user.block.menu:  # used to display the menu in profile pages
      sonata.user.block.account: # used to display menu option (login option)
      sonata.block.service.text: # used to if you plan to use Sonata user routes

sonata_user:
    security_acl: true # Uncomment for ACL support
    #security_acl: false
    manager_type: orm # can be orm or mongodb

sonata_admin:
    security:
        handler: sonata.admin.security.handler.acl
        # acl security information
        information:
            GUEST:    [VIEW, LIST]
            STAFF:    [EDIT, LIST, CREATE]
            EDITOR:   [OPERATOR, EXPORT]
            ADMIN:    [MASTER]
        # permissions not related to an object instance and also to be available when objects do not exist
        # the DELETE admin permission means the user is allowed to batch delete objects
        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]
        # permission related to the objects
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]
    title:      Department Site
    title_logo: /bundles/sonataadmin/logo_title.png


fos_user:
    db_driver:  orm # can be orm or odm
    firewall_name:  main
    user_class:   Application\Sonata\UserBundle\Entity\User

    group:
      group_class:  Application\Sonata\UserBundle\Entity\Group
      group_manager: sonata.user.orm.group_manager

    service:
      user_manager: sonata.user.orm.user_manager
