imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: sonata/admin_config.yml }
    - { resource: sonata/fos_config.yml }
    - { resource: ivory/ivory_config.yml }
    - { resource: elfinder/elfinder_config.yml }
    - { resource: a2lix_translation_form/a2lix_translation_form_config.yml }
    - { resource: liip/liip_config.yml }
    - { resource: itm/itm_config.yml }
    - { resource: knp_paginator/knp_paginator_config.yml }
    - { resource: pugx_multi_user/pugx_multi_user_config.yml }
    - { resource: "../../vendor/knplabs/doctrine-behaviors/config/orm-services.yml" }



# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: ru

framework:
    #esi:             ~
    translator:
            paths:
                    - "%kernel.root_dir%/Resources/translations"
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  ru
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'ITMFilePreviewBundle:Form:fields.html.twig'
        - 'ITMImagePreviewBundle:Form:fields.html.twig'
        - 'bootstrap_3_layout.html.twig'


# Doctrine Configuration
doctrine:
    dbal:
        mapping_types:
                enum:       string
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
          json: Sonata\Doctrine\Types\JsonType
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                auto_mapping: true

  # Swiftmailer Configuration

swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

sonata_admin:
    title: 'Department Site'


sonata_block:
    default_contexts: [cms]
    blocks:
      # Enable the SonataAdminBundle block
      sonata.admin.block.admin_list:
        contexts:  [admin]




