security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        USERS:
             - ROLE_ADMIN_USER_VIEW
             - ROLE_ADMIN_USER_LIST
             - ROLE_ADMIN_USER_EDIT

        STUDENT_USER:
             - ROLE_ADMIN_STUDENT_USER_EDIT
             - ROLE_ADMIN_STUDENT_USER_CREATE
             - ROLE_ADMIN_STUDENT_USER_DELETE
             - ROLE_ADMIN_STUDENT_USER_VIEW
             - ROLE_ADMIN_STUDENT_USER_LIST

        TEACHER_USER:
            - ROLE_ADMIN_TEACHER_USER_EDIT
            - ROLE_ADMIN_TEACHER_USER_CREATE
            - ROLE_ADMIN_TEACHER_USER_DELETE
            - ROLE_ADMIN_TEACHER_USER_VIEW
            - ROLE_ADMIN_TEACHER_USER_LIST

        PARENT_USER:
            - ROLE_ADMIN_PARENT_USER_EDIT
            - ROLE_ADMIN_PARENT_USER_CREATE
            - ROLE_ADMIN_PARENT_USER_DELETE
            - ROLE_ADMIN_PARENT_USER_VIEW
            - ROLE_ADMIN_PARENT_USER_LIST

        PROJECTS:
            - ROLE_ADMIN_PROJECT_EDIT
            - ROLE_ADMIN_PROJECT_CREATE
            - ROLE_ADMIN_PROJECT_VIEW
            - ROLE_ADMIN_PROJECT_DELETE
            - ROLE_ADMIN_PROJECT_LIST

        COMMENT:
            - ROLE_ADMIN_COMMENT_EDIT
            - ROLE_ADMIN_COMMENT_CREATE
            - ROLE_ADMIN_COMMENT_VIEW
            - ROLE_ADMIN_COMMENT_DELETE
            - ROLE_ADMIN_COMMENT_LIST

        DICTIONARY:
            - ROLE_ADMIN_DICTIONARY_EDIT
            - ROLE_ADMIN_DICTIONARY_CREATE
            - ROLE_ADMIN_DICTIONARY_VIEW
            - ROLE_ADMIN_DICTIONARY_DELETE
            - ROLE_ADMIN_DICTIONARY_LIST

        NOTICE:
            - ROLE_ADMIN_NOTICE_EDIT
            - ROLE_ADMIN_NOTICE_CREATE
            - ROLE_ADMIN_NOTICE_VIEW
            - ROLE_ADMIN_NOTICE_DELETE
            - ROLE_ADMIN_NOTICE_LIST

        GALLERY:
            - ROLE_ADMIN_GALLERY_EDIT
            - ROLE_ADMIN_GALLERY_CREATE
            - ROLE_ADMIN_GALLERY_VIEW
            - ROLE_ADMIN_GALLERY_DELETE
            - ROLE_ADMIN_GALLERY_LIST
            - ROLE_ADMIN_IMAGE_EDIT
            - ROLE_ADMIN_IMAGE_CREATE
            - ROLE_ADMIN_IMAGE_VIEW
            - ROLE_ADMIN_IMAGE_DELETE
            - ROLE_ADMIN_IMAGE_LIST

        MENU:
            - ROLE_ADMIN_SIDE_BAR_MENU_EDIT
            - ROLE_ADMIN_SIDE_BAR_MENU_CREATE
            - ROLE_ADMIN_SIDE_BAR_MENU_VIEW
            - ROLE_ADMIN_SIDE_BAR_MENU_DELETE
            - ROLE_ADMIN_SIDE_BAR_MENU_LIST
            - ROLE_ADMIN_BANNER_MENU_EDIT
            - ROLE_ADMIN_BANNER_MENU_CREATE
            - ROLE_ADMIN_BANNER_MENU_VIEW
            - ROLE_ADMIN_BANNER_MENU_DELETE
            - ROLE_ADMIN_BANNER_MENU_LIST
            - ROLE_ADMIN_HEADER_MENU_EDIT
            - ROLE_ADMIN_HEADER_MENU_CREATE
            - ROLE_ADMIN_HEADER_MENU_VIEW
            - ROLE_ADMIN_HEADER_MENU_DELETE
            - ROLE_ADMIN_HEADER_MENU_LIST

        NEWS:
            - ROLE_ADMIN_NEWS_EDIT
            - ROLE_ADMIN_NEWS_CREATE
            - ROLE_ADMIN_NEWS_VIEW
            - ROLE_ADMIN_NEWS_DELETE
            - ROLE_ADMIN_NEWS_LIST

        PAGE:
            - ROLE_ADMIN_PAGE_EDIT
            - ROLE_ADMIN_PAGE_CREATE
            - ROLE_ADMIN_PAGE_VIEW
            - ROLE_ADMIN_PAGE_DELETE
            - ROLE_ADMIN_PAGE_LIST

        SLIDE_SHOW:
            - ROLE_ADMIN_SLIDE_SHOW_EDIT
            - ROLE_ADMIN_SLIDE_SHOW_CREATE
            - ROLE_ADMIN_SLIDE_SHOW_VIEW
            - ROLE_ADMIN_SLIDE_SHOW_DELETE
            - ROLE_ADMIN_SLIDE_SHOW_LIST

        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, USERS]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        admin:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                login_path: /admin/login
                csrf_token_generator: security.csrf.token_manager
            logout: true
            anonymous: true

        main:
            form_login:
                provider: fos_userbundle
                login_path: /login
                csrf_token_generator: security.csrf.token_manager
            logout: true

            anonymous:    true

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/admin/, role: ROLE_ADMIN }
       