page_index:
    path:     /
    defaults: { _controller: "DepartmentSitePageBundle:Page:index" }
    methods:  GET

page_show:
    path:     /{slug}/show
    defaults: { _controller: "DepartmentSitePageBundle:Page:show" }
    methods:  GET
