page_index:
    path:     /
    defaults: { _controller: "DepartmentSitePageBundle:Page:index" }
    methods:  GET

page_show:
    path:     /{slug}/show
    defaults: { _controller: "DepartmentSitePageBundle:Page:show" }
    methods:  GET

page_new:
    path:     /new
    defaults: { _controller: "DepartmentSitePageBundle:Page:new" }
    methods:  [GET, POST]

page_edit:
    path:     /{slug}/edit
    defaults: { _controller: "DepartmentSitePageBundle:Page:edit" }
    methods:  [GET, POST]

page_delete:
    path:     /{slug}/delete
    defaults: { _controller: "DepartmentSitePageBundle:Page:delete" }
    methods:  DELETE
