#page_index:
#    path:     /
#    defaults:
#        _controller: "DepartmentSitePageBundle:Page:index"
#        locale: ru
#    methods:  GET
#    requirements: ru|en

show:
    path:     /{slug}/show
    defaults:
        _controller: "DepartmentSitePageBundle:Page:show"
#        locale: ru
    methods:  GET
    requirements:
#        locale : ru|en
