pugx_multi_user:
    users:
        student_user:
            entity:
                class: Application\FOS\UserBundle\Entity\StudentUser
#          factory:
            registration:
                form:
                    type: Application\FOS\UserBundle\Form\Type\RegistrationStudentUserFormType
                    name: fos_user_registration_form_student_user
                    validation_groups:  [Registration, Default]
                template: ApplicationFOSUserBundle:Registration:user.form.html.twig
#        profile:
#          form:
#            type: Acme\UserBundle\Form\Type\ProfileUserOneFormType
#            name: fos_user_profile_form
#            validation_groups:  [Profile, Default]
        parent_user:
            entity:
                class: Application\FOS\UserBundle\Entity\ParentUser
            registration:
                form:
                    type: Application\FOS\UserBundle\Form\Type\RegistrationParentUserFormType
                    name: fos_user_registration_form_parent_user
                    validation_groups:  [Registration, Default]
                template: ApplicationFOSUserBundle:Registration:user.form.html.twig
        teacher_user:
            entity:
                class: Application\FOS\UserBundle\Entity\TeacherUser
            registration:
                form:
                    type: Application\FOS\UserBundle\Form\Type\RegistrationTeacherUserFormType
                    name: fos_user_registration_form_teacher_user
                    validation_groups:  [Registration, Default]
                template: ApplicationFOSUserBundle:Registration:user.form.html.twig