version: "2"

services:

    php:
        image: ${REGISTRY_URL}${REPOSITORY_NAME}php:${DOCKER_TAG}
        build:
            context: './../'
            dockerfile: 'docker/php/Dockerfile'
        environment:
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_NAME=${DB_NAME}
            - DB_PASS=${DB_PASS}
            - DB_USER=${DB_USER}
        volumes:
            - "${JWT_PRIVATE_KEY_PATH}:/keys/jwt_private.pem:ro"
            - "${JWT_PUBLIC_KEY_PATH}:/keys/jwt_public.pem:ro"

    front:
        image: ${REGISTRY_URL}${REPOSITORY_NAME}front:${DOCKER_TAG}
        build: 'nginx'
        depends_on:
            - php
        volumes:
            - "${FRONTEND_HOME}:/srv:ro"
            - "/certs/domain.crt:/certs/domain.crt:ro"
            - "/certs/domain.key:/certs/domain.key:ro"

