version: "2"

services:
#    front:
#        environment:
#            - USE_CORS_PROXY=yes

    database:
        image: mysql/mysql-server:5.7
        environment:
            - MYSQL_USER=${DB_USER}
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_PASSWORD=${DB_PASS}
            - MYSQL_ROOT_PASSWORD=${DB_PASS}
        volumes:
          - ./mysql:/var/lib/mysql
        ports:
          - 3306:3306

#    docker_monitoring:
#        image: portainer/portainer:1.13.5
#        ports:
#            - 0.0.0.0:8080:9000
#        volumes:
#            - /var/run/docker.sock:/var/run/docker.sock
#        entrypoint:
#            - /portainer
#            - --admin-password
#            - ${PORTAINER_PASS}
#            - -H
#            - unix:///var/run/docker.sock
