services:
    admin.project:
        class: DepartmentSite\ProjectBundle\Admin\ProjectAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Project", label: "Project" }
        arguments: [~, DepartmentSite\ProjectBundle\Entity\Project, ~]
        calls:
            - [ setTranslationDomain, [DepartmentSiteProjectBundle]]

    admin.comment:
        class: DepartmentSite\ProjectBundle\Admin\CommentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Project", label: "Comment" }
        arguments:
            - ~
            - DepartmentSite\ProjectBundle\Entity\Comment
            - DepartmentSiteProjectBundle:CommentAdmin
            - ~
        calls:
            - [ setTranslationDomain, [DepartmentSiteProjectBundle]]
            - [ setTemplate, [list, DepartmentSiteProjectBundle:ProjectAdmin:list.html.twig]]
