department_site_gallery_image:
    resource: "@DepartmentSiteGalleryBundle/Resources/config/routing/image.yml"
    prefix:   /image
department_site_gallery_gallery:
    resource: "@DepartmentSiteGalleryBundle/Resources/config/routing/gallery.yml"
    prefix:   /{_locale}/gallery
