services:
  admin.gallery:
          class: DepartmentSite\GalleryBundle\Admin\GalleryAdmin
          tags:
              - { name: sonata.admin, manager_type: orm, group: "Gallery", label: "Gallery" }
          arguments: [~, DepartmentSite\GalleryBundle\Entity\Gallery, ~]
          calls:
               - [ setTranslationDomain, [DepartmentSiteGalleryBundle]]

  admin.image:
          class: DepartmentSite\GalleryBundle\Admin\ImageAdmin
          tags:
               - { name: sonata.admin, manager_type: orm, group: "Gallery", label: "Image", show_in_dashboard: false }
          arguments: [~, DepartmentSite\GalleryBundle\Entity\Image, ~]
          calls:
               - [ setTranslationDomain, [DepartmentSiteGalleryBundle]]
