services:
    admin.gallery:
        class: DepartmentSite\GalleryBundle\Admin\GalleryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Gallery", label: "Gallery" }
        arguments: [~, DepartmentSite\GalleryBundle\Entity\Gallery, ~]
        calls:
            - [ setTranslationDomain, [DepartmentSiteGalleryBundle]]
