services:
    admin.page:
        class: DepartmentSite\PageBundle\Admin\PageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Page", label: "Page" }
        arguments: [~, DepartmentSite\PageBundle\Entity\Page, ~]
        calls:
            - [ setTranslationDomain, [DepartmentSitePageBundle]]