services:
  admin.slide.show:
          class: DepartmentSite\SlideShowBundle\Admin\SlideShowAdmin
          tags:
              - { name: sonata.admin, manager_type: orm, group: "Slide Show", label: "Slide Show" }
          arguments: [~, DepartmentSite\SlideShowBundle\Entity\SlideShow, ~]
          calls:
              - [ setTranslationDomain, [DepartmentSiteSlideShowBundle]]
