liip_imagine:
    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~
        preview:
            quality: 75
            filters:
                thumbnail: { size: [232, 232], mode: outbound }
