#services:
#   app.form.registration:
#       class: Application\FOS\UserBundle\Form\Type\RegistrationStudentUserFormType
#       tags:
#           - { name: form.type, alias: fos_user_registration_form }