advert_index:
    path:     /{page}
    defaults: { _controller: "DepartmentSiteAdvertBundle:Advert:index" }
    methods:  GET

advert_show:
    path:     /{slug}/show
    defaults: { _controller: "DepartmentSiteAdvertBundle:Advert:show" }
    methods:  GET

advert_new:
    path:     /new
    defaults: { _controller: "DepartmentSiteAdvertBundle:Advert:new" }
    methods:  [GET, POST]


