news_index:
    path:     /{page}/
    defaults:
        _controller: "DepartmentSiteNewsBundle:News:index"
        _locale : ru
        page : 1
    methods:  GET
    requirements:
        _locale : ru|en

news_show:
    path:     /{slug}/show
    defaults:
        _controller: "DepartmentSiteNewsBundle:News:show"
        _locale: ru
    methods:  GET
    requirements:
        _locale : ru|en

