news_index:
    path:     /{page}
    defaults: { _controller: "DepartmentSiteNewsBundle:News:index" }
    methods:  GET

news_show:
    path:     /{slug}/show
    defaults: { _controller: "DepartmentSiteNewsBundle:News:show" }
    methods:  GET


