services:
    department_site_news.subscriber:
        class: DepartmentSite\NewsBundle\EventListener\ImagePreviewSubscriber
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_subscriber, connection: default }
