services:
    admin.news:
        class: DepartmentSite\NewsBundle\Admin\NewsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "News", label: "News" }
        arguments: [~, DepartmentSite\NewsBundle\Entity\News, ~]
        calls:
             - [ setTranslationDomain, [DepartmentSiteNewsBundle]]
