a2lix_translation_form:
    locale_provider: default
    locales: [ru, en]
    default_locale: "%locale%"
    required_locales: "%locale%"
    manager_registry: doctrine
    templating: "A2lixTranslationFormBundle::default.html.twig"