services:
    admin.advert:
        class: DepartmentSite\AdvertBundle\Admin\AdvertAdmin
        arguments: [~, DepartmentSite\AdvertBundle\Entity\Advert, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Advert", label: Advert}
        calls:
              - [ setTranslationDomain, [DepartmentSiteAdvertBundle]]